# Generated by Django 4.1.3 on 2023-01-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
