# Generated by Django 4.1.3 on 2023-01-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_alter_favorite_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
