# Generated by Django 4.1.3 on 2023-01-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_kind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('skin_type', models.CharField(blank=True, max_length=100)),
                ('skin_care_benefits', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('shelf', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.CharField(blank=True, max_length=100)),
                ('stock', models.CharField(blank=True, max_length=100)),
                ('ship', models.CharField(blank=True, max_length=100)),
                ('Description', models.TextField(blank=True)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_kind.kind')),
            ],
        ),
    ]
