# Generated by Django 4.1.3 on 2023-01-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
