# Generated by Django 4.1.3 on 2023-01-15 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_products_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='likey',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
